-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "deployment_status" AS ENUM('DEV', 'STABLE', 'OUT');CREATE TABLE "command_logs" (
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"interaction_token" text NOT NULL,
	"command_id" integer,
	"user_id" varchar(30) NOT NULL,
	"user_username" varchar(32) NOT NULL,
	"guild_id" varchar(30),
	"guild_name" varchar(100),
	"channel_id" varchar(30),
	"channel_name" varchar(100),
	"command_name" text NOT NULL,
	"options" jsonb,
	"dm" boolean NOT NULL,
	"locale" varchar(10) NOT NULL
);
CREATE TABLE "commands" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "commands_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" integer NOT NULL,
	"deployment_status" "deployment_status" DEFAULT 'STABLE'::"deployment_status" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"description" text,
	CONSTRAINT "type_value" CHECK (((type >= 1) AND (type <= 4)))
);
CREATE TABLE "guilds" (
	"guild_id" varchar(30) PRIMARY KEY,
	"member_counter_channel_id" varchar(30),
	"member_counter_style" text,
	"welcome_channel_id" varchar(30),
	"welcome_message" varchar(2000),
	"mission_brief" jsonb,
	"brief_channel" varchar(30)
);
CREATE TABLE "mcstatus" (
	"guild_id" varchar(30) PRIMARY KEY,
	"address" varchar(45),
	"port" integer DEFAULT 25565,
	"counter_channel_id" varchar(30),
	"counter_style" text
);
CREATE TABLE "warns" (
	"warn_id" varchar(25) PRIMARY KEY,
	"user_id" varchar(30) NOT NULL,
	"guild_id" varchar(30) NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"reason_title" text NOT NULL,
	"reason_description" text,
	"creator_id" text NOT NULL
);
CREATE INDEX "command_logs_command_id_idx" ON "command_logs" ("command_id");ALTER TABLE "command_logs" ADD CONSTRAINT "command_logs_commands_id_fk" FOREIGN KEY ("command_id") REFERENCES "commands"("id") ON DELETE SET NULL ON UPDATE RESTRICT;
*/